package AdminLogin;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class AdminFunctionsController {
	@FXML
	private AnchorPane adminFunctions;

	// Event Listener on Button.onAction
	@FXML
	public void viewStats(ActionEvent event) {
		Statistics stats = new Statistics();
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void createQuestion(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void modifyQuestion(ActionEvent event) {
		// TODO Autogenerated
	}
}
